//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VP.Sharepoint.CQ.UserControls {
    
    
    public partial class ProfilesView {
        
        /// <summary>
        /// ddlCategory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        
        /// <summary>
        /// viewProfiles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VP.Sharepoint.CQ.Core.WebControls.FlatDataView viewProfiles;
        
        /// <summary>
        /// fName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VP.Sharepoint.CQ.Core.WebControls.TextFieldRef fName;
        
        /// <summary>
        /// fPosition control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VP.Sharepoint.CQ.Core.WebControls.TextFieldRef fPosition;
        
        /// <summary>
        /// TextFieldRef1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VP.Sharepoint.CQ.Core.WebControls.TextFieldRef TextFieldRef1;
        
        /// <summary>
        /// TextFieldRef2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VP.Sharepoint.CQ.Core.WebControls.TextFieldRef TextFieldRef2;
        
        /// <summary>
        /// TextFieldRef3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VP.Sharepoint.CQ.Core.WebControls.TextFieldRef TextFieldRef3;
        
        /// <summary>
        /// TextFieldRef4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VP.Sharepoint.CQ.Core.WebControls.TextFieldRef TextFieldRef4;
        
        /// <summary>
        /// TextFieldRef5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VP.Sharepoint.CQ.Core.WebControls.TextFieldRef TextFieldRef5;
        
        /// <summary>
        /// TextFieldRef6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VP.Sharepoint.CQ.Core.WebControls.TextFieldRef TextFieldRef6;
        
        /// <summary>
        /// TextFieldRef7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VP.Sharepoint.CQ.Core.WebControls.TextFieldRef TextFieldRef7;
        
        /// <summary>
        /// sOrder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::VP.Sharepoint.CQ.Core.WebControls.SortFieldRef sOrder;
    }
}
